### PR TITLE
Update Tim

### PR DESCRIPTION
**Pull request by timcreasy**

### CODE REVIEW

**Comment by timcreasy** [comment]
@sscotth are you able to merge this?

**Comment by sscotth** [comment]
@timcreasy 

Sure, no problem. Is there a placeholder image we can use instead? Do you want to remove [tim-2.jpg](https://github.com/nss-day-cohort-14/nss-day-cohort-14.github.io/blob/5657043cf2177569e4e1368c5cf433e9d9898b56/img/tim-2.jpg) as well?

**Comment by sscotth** [comment]
How about this?

image

**Comment by timcreasy** [comment]
> How about this?
> 
> image

Great idea - added in https://github.com/nss-day-cohort-14/nss-day-cohort-14.github.io/pull/37/commits/c5b8204d9292b202139932d5783a2920e392dac5

**Pull request merged**
